set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T4} [get_ports tx]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N5} [get_ports rx]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P17} [get_ports fpga_clk]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P15} [get_ports fpga_rst_in]


set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R1} [get_ports switch2N4_in[0]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N4} [get_ports switch2N4_in[1]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M4} [get_ports switch2N4_in[2]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R2} [get_ports switch2N4_in[3]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P2} [get_ports switch2N4_in[4]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P3} [get_ports switch2N4_in[5]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P4} [get_ports switch2N4_in[6]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P5} [get_ports switch2N4_in[7]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T5} [get_ports switch2N4_in[8]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T3} [get_ports switch2N4_in[9]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R3} [get_ports switch2N4_in[10]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V4} [get_ports switch2N4_in[11]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V5} [get_ports switch2N4_in[12]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V2} [get_ports switch2N4_in[13]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U2} [get_ports switch2N4_in[14]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U3} [get_ports switch2N4_in[15]]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K3} [get_ports led2N4[0]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M1} [get_ports led2N4[1]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L1} [get_ports led2N4[2]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K6} [get_ports led2N4[3]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J5} [get_ports led2N4[4]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN H5} [get_ports led2N4[5]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN H6} [get_ports led2N4[6]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K1} [get_ports led2N4[7]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K2} [get_ports led2N4[8]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J2} [get_ports led2N4[9]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J3} [get_ports led2N4[10]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN H4} [get_ports led2N4[11]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J4} [get_ports led2N4[12]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN G3} [get_ports led2N4[13]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN G4} [get_ports led2N4[14]]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN F6} [get_ports led2N4[15]]

##vga
set_property PACKAGE_PIN D7 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property PACKAGE_PIN C4 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN F5 [get_ports vga_rgb[0]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_rgb[0]]
set_property PACKAGE_PIN C6 [get_ports vga_rgb[1]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_rgb[1]]
set_property PACKAGE_PIN C5 [get_ports vga_rgb[2]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_rgb[2]]
set_property PACKAGE_PIN B7 [get_ports vga_rgb[3]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_rgb[3]]
set_property PACKAGE_PIN B6 [get_ports vga_rgb[4]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_rgb[4]]
set_property PACKAGE_PIN A6 [get_ports vga_rgb[5]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_rgb[5]]
set_property PACKAGE_PIN A5 [get_ports vga_rgb[6]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_rgb[6]]
set_property PACKAGE_PIN D8 [get_ports vga_rgb[7]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_rgb[7]]
set_property PACKAGE_PIN C7 [get_ports vga_rgb[8]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_rgb[8]]
set_property PACKAGE_PIN E6 [get_ports vga_rgb[9]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_rgb[9]]
set_property PACKAGE_PIN E5 [get_ports vga_rgb[10]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_rgb[10]]
set_property PACKAGE_PIN E7 [get_ports vga_rgb[11]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_rgb[11]]
